#!/usr/bin/env bash
# =============================================================================
# claude-plugin-template - Setup Proxy Script
# =============================================================================
#
# Auto-generated by claude-binary-plugin prepare.
# This script wraps SessionStart hooks to provide just-in-time compilation.
#
# Fast path: binary exists + node_modules present -> exec to binary
# Slow path: buffer stdin -> lock -> bun install -> build -> forward stdin
# Error path: emit JSON with additionalContext to stdout + error to stderr + exit 2
#
# DO NOT EDIT - regenerate with: claude-binary-plugin prepare
# =============================================================================

{
set -euo pipefail

BINARY_NAME="claude-plugin-template.plugin"
CONFIG_FILE="plugin.config.ts"
PLUGIN_NAME="claude-plugin-template"

# Resolve plugin root from this script's location
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
BINARY_PATH="${PLUGIN_DIR}/${BINARY_NAME}"

# Override CLAUDE_PLUGIN_ROOT if not set (for manual testing)
CLAUDE_PLUGIN_ROOT="${CLAUDE_PLUGIN_ROOT:-${PLUGIN_DIR}}"

# Lock configuration
LOCK_DIR="${PLUGIN_DIR}/.build-lock"
LOCK_STALE_SECONDS=300

# -----------------------------------------------------------------------------
# Portable stat: get file modification time in epoch seconds
# -----------------------------------------------------------------------------
get_mtime() {
    local target="$1"
    # macOS stat
    if stat -f %m "${target}" 2>/dev/null; then
        return
    fi
    # GNU/Linux stat
    stat -c %Y "${target}" 2>/dev/null
}

# -----------------------------------------------------------------------------
# Error handler: inform Claude via additionalContext and exit cleanly
# -----------------------------------------------------------------------------
emit_error() {
    local msg="$1"
    echo "{\"additionalContext\":\"[Plugin Build Error] The ${PLUGIN_NAME} plugin failed to build on this machine. Error: ${msg}. The plugin hooks and commands will not be available this session. To retry, delete the plugin cache and restart the session.\"}" >&1
    echo "[${PLUGIN_NAME}] ERROR: ${msg}" >&2
    exit 2
}

# -----------------------------------------------------------------------------
# Lock acquisition (mkdir-based, portable)
# -----------------------------------------------------------------------------
acquire_lock() {
    # Check for stale lock
    if [ -d "${LOCK_DIR}" ]; then
        local lock_mtime
        lock_mtime="$(get_mtime "${LOCK_DIR}" 2>/dev/null || echo 0)"
        local now
        now="$(date +%s)"
        local age=$(( now - lock_mtime ))
        if [ "${age}" -gt "${LOCK_STALE_SECONDS}" ]; then
            rmdir "${LOCK_DIR}" 2>/dev/null || true
        fi
    fi

    # Try to acquire
    if ! mkdir "${LOCK_DIR}" 2>/dev/null; then
        # Another process holds the lock - wait for it
        local waited=0
        while [ -d "${LOCK_DIR}" ] && [ "${waited}" -lt "${LOCK_STALE_SECONDS}" ]; do
            sleep 1
            waited=$(( waited + 1 ))
        done

        # Re-check: binary might have been built by the other process
        if [ -x "${BINARY_PATH}" ]; then
            return 1  # Signal: skip build, binary is ready
        fi

        # Try again
        if ! mkdir "${LOCK_DIR}" 2>/dev/null; then
            emit_error "Could not acquire build lock after ${waited}s"
        fi
    fi

    # Clean up lock on exit
    trap 'rmdir "${LOCK_DIR}" 2>/dev/null || true' EXIT
    return 0
}

# -----------------------------------------------------------------------------
# Build the plugin binary
# -----------------------------------------------------------------------------
build_plugin() {
    echo "[${PLUGIN_NAME}] Installing dependencies..." >&2
    if ! (cd "${PLUGIN_DIR}" && bun install --silent 2>&1) >&2; then
        emit_error "bun install failed"
    fi

    echo "[${PLUGIN_NAME}] Building plugin binary..." >&2
    if ! (cd "${PLUGIN_DIR}" && bun x claude-binary-plugin build "${CONFIG_FILE}" --no-persist --quiet 2>&1) >&2; then
        emit_error "Plugin build failed"
    fi

    if [ ! -x "${BINARY_PATH}" ]; then
        # Try chmod in case build produced a non-executable file
        chmod +x "${BINARY_PATH}" 2>/dev/null || true
        if [ ! -x "${BINARY_PATH}" ]; then
            emit_error "Build completed but binary not found at ${BINARY_PATH}"
        fi
    fi
}

# =============================================================================
# Main
# =============================================================================

# Fast path: binary exists and node_modules present -> exec directly
if [ -x "${BINARY_PATH}" ] && [ -d "${PLUGIN_DIR}/node_modules" ]; then
    exec "${BINARY_PATH}" "$@"
fi

# Slow path: need to build
# Buffer stdin so we can forward it after building
STDIN_BUFFER="$(cat)"

# Acquire build lock (returns 1 if another process already built it)
if acquire_lock; then
    # Double-check after acquiring lock
    if [ ! -x "${BINARY_PATH}" ] || [ ! -d "${PLUGIN_DIR}/node_modules" ]; then
        build_plugin
    fi
fi

# Forward buffered stdin to the binary
echo "${STDIN_BUFFER}" | exec "${BINARY_PATH}" "$@"
}
